image:
  name: peterzel/scala-sbt
stages:
    - build
    - test
    - slowtest
#    - bench
compile:
  stage: build
  script: sbt compile
test:
  stage: test
  script: sbt test
slowtest:
  stage: slowtest
  script: sbt slow:test
#bench:
#  stage: bench
#  script: sbt 'runMain crdtver.bench.Benchmark'
before_cache:
  script:
    - rm -fv $HOME/.ivy2/.sbt.ivy.lock
    - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
    - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  untracked: true
  paths:
    - "$HOME/.sbt"
    - "$HOME/.ivy2/cache"
    - "$HOME/.cache/coursier"
    - "$HOME/.npm"