image:
  name: peterzel/scala-sbt
compile:
  stage: build
  script:
    - sbt compile
    - sbt test
    - sbt slow:test
before_cache:
  script:
    - rm -fv $HOME/.ivy2/.sbt.ivy.lock
    - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
    - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  untracked: true
  paths:
    - "$HOME/.sbt"
    - "$HOME/.ivy2/cache"
    - "$HOME/.cache/coursier"
    - "$HOME/.npm"