image:
  name: peterzel/scala-sbt
compile:
  stage: build
  script:
    - sbt compile
    - sbt test
    - sbt slow:test
cache:
  untracked: true
  paths:
    - "/root/.sbt"
    - "/root/.ivy2"
    - "/root/.cache/coursier"
    - "/root/.npm"